oauth2:
  user:
    google:
      client-id: "${GOOGLE_CLIENT_ID}"
      client-secret: "${GOOGLE_CLIENT_SECRET}"
      redirect-url: http://localhost:8080/redirect/oauth

jwt:
  secret-key: "${JWT_SECRET}"